const {Client}=require('openrgb-sdk');
let queue=Promise.resolve();
const {colorMode,restoredMode}=require('./lighting-policy');
const key=d=>`${d.name}|${d.location}|${d.serial}`;
function session(fn){const job=queue.then(()=>new Promise((resolve,reject)=>{const c=new Client('Foxsocket',6742,'127.0.0.1');let done=false;const finish=(err,value)=>{if(done)return;done=true;clearTimeout(timer);c.socket?.destroy();err?reject(err):resolve(value);};c.on('error',e=>finish(e));const timer=setTimeout(()=>finish(Error('OpenRGB did not respond within 8 seconds.')),8000);(async()=>{await c.connect();const n=await c.getControllerCount();if(n>64)throw Error('Unexpected device count');const devices=[];for(let i=0;i<n;i++)devices.push(await c.getControllerData(i));return fn(c,devices);})().then(v=>finish(null,v),finish);}));queue=job.catch(()=>{});return job;}
async function discover(){return session(async(c,devices)=>devices.map(d=>({key:key(d),name:d.name,location:d.location,leds:d.colors.length,modes:d.modes.map(m=>m.name),zones:d.zones.map(z=>({name:z.name,count:z.ledsCount})),supported:!!colorMode(d)&&d.colors.length>0,activeMode:d.modes.find(m=>m.id===d.activeMode)?.name,colors:d.colors})));}
async function apply(keys,hex,brightness,onSnapshot){if(!Array.isArray(keys)||!keys.length)throw Error('Select at least one device');if(!/^#[0-9a-f]{6}$/i.test(hex)||!Number.isInteger(brightness)||brightness<0||brightness>100)throw Error('Invalid color or brightness');return session(async(c,devices)=>{const targets=devices.filter(d=>keys.includes(key(d)));if(targets.length!==keys.length)throw Error('A selected device disconnected. Refresh devices before applying.');for(const d of targets)if(!!!colorMode(d)||!d.colors.length)throw Error(`${d.name} has no supported static color mode`);const snapshots=targets.map(d=>({key:key(d),mode:d.modes.find(m=>m.id===d.activeMode),colors:d.colors}));await onSnapshot(snapshots);const color={red:Math.round(parseInt(hex.slice(1,3),16)*brightness/100),green:Math.round(parseInt(hex.slice(3,5),16)*brightness/100),blue:Math.round(parseInt(hex.slice(5,7),16)*brightness/100)};const results=[];for(const d of targets){try{const mode=colorMode(d);await c.updateMode(d.deviceId,{...mode,brightness:mode.brightnessMax||0,colors:mode.colors.length?mode.colors.map(()=>color):[]});await c.updateLeds(d.deviceId,Array(d.colors.length).fill(color));const after=await c.getControllerData(d.deviceId);results.push({name:d.name,ok:after.activeMode===mode.id&&after.colors.every(v=>v.red===color.red&&v.green===color.green&&v.blue===color.blue),zeroZones:d.zones.filter(z=>z.ledsCount===0).map(z=>z.name)});}catch(e){results.push({name:d.name,ok:false,error:e.message});}}return results;});}
async function restore(snapshots){if(!Array.isArray(snapshots)||!snapshots.length||snapshots.length>64)throw Error('No valid previous lighting state saved');return session(async(c,devices)=>{const results=[];for(const s of snapshots){if(!s||typeof s.key!=='string')throw Error('Invalid lighting snapshot');const d=devices.find(d=>key(d)===s.key);if(!d){results.push({name:s.key,ok:false});continue;}try{const mode=restoredMode(d,s);await c.updateMode(d.deviceId,mode);await c.updateLeds(d.deviceId,s.colors);const after=await c.getControllerData(d.deviceId);results.push({name:d.name,ok:after.activeMode===s.mode.id&&after.colors.length===s.colors.length&&after.colors.every((c,i)=>['red','green','blue'].every(k=>c[k]===s.colors[i][k]))});}catch{results.push({name:d.name,ok:false});}}return results;});}
module.exports={discover,apply,restore};
