const {app,BrowserWindow,ipcMain,Tray,Menu,shell,dialog}=require('electron');
const fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto');
const {execFile}=require('child_process');
let win,tray,quitting=false,busy=false; let state;
const modes=['Focus','Gaming','Relax','Away'];
const lighting=require('./lighting');
const brand=require('./branding');
const setup=require('./setup');
require('./updates-main')(()=>win);
const {clawArgs}=require('./host-manager');
const hostManager=require('./host-main')(()=>win,()=>busy);
const sceneColors={Focus:'#00c9f4',Gaming:'#b58bff',Relax:'#56dfbc',Away:'#000000'};
const run=(exe,args,timeout=15000)=>new Promise((resolve,reject)=>execFile(exe,args,{windowsHide:true,timeout,maxBuffer:8*1024*1024,encoding:'utf8'},(e,out)=>e?reject(new Error(e.killed?'Operation timed out.':'The command failed. Check the gateway setup and try again.')):resolve(out)));
const claw=(args,timeout)=>run('wsl.exe',clawArgs(state?.connection?.distro||'Ubuntu-24.04',args),timeout);
const parse=(s)=>{let start=s.indexOf('{');if(start<0)throw Error('Gateway returned no JSON response');return JSON.parse(s.slice(start));};
function persist(){const file=path.join(app.getPath('userData'),'state.json');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file+'.tmp',JSON.stringify(state,null,2));fs.renameSync(file+'.tmp',file);}
function log(text){state.activity.unshift({text,time:Date.now()});state.activity=state.activity.slice(0,80);persist();}
function load(){try{state=JSON.parse(fs.readFileSync(path.join(app.getPath('userData'),'state.json'),'utf8'));}catch(error){if(error.code!=='ENOENT')throw Error('Your saved workspace could not be read. It has not been replaced. Restore a backup or contact support.');state={version:1,tasks:[],notes:'',mode:'Focus',timer:null,chat:[],folders:[],activity:[],closeToTray:false};}if(!state.session)state.session='agent:main:command-center-'+crypto.randomUUID();let installerChoice;try{if(app.isPackaged)installerChoice=JSON.parse(fs.readFileSync(path.join(process.resourcesPath,'installer-role.json'),'utf8'));}catch{}state.setup=setup.fromInstaller(state.setup,installerChoice);persist();}
async function applyLighting(options){
 const results=await lighting.apply(options.keys,options.color,options.brightness,async snapshots=>{state.lightingSnapshot=snapshots;persist();});
 state.lighting={...state.lighting,...options};
 log('Lighting: '+results.map(r=>r.name+': '+(r.ok?'state verified':'not confirmed')).join(', '));
 return {results,state};
}
async function setMode(mode){if(!modes.includes(mode))throw Error('Invalid mode');state.mode=mode;log(mode+' workspace mode selected.');if(state.lighting?.sync){try{await applyLighting({...state.lighting,color:sceneColors[mode]});}catch(e){log('Lighting unavailable: '+e.message);}}win?.webContents.send('state',state);return state;}function createWindow(){win=new BrowserWindow({width:1440,height:960,minWidth:760,minHeight:600,backgroundColor:'#080e17',title:brand.productName,icon:path.join(__dirname,'assets/icon.png'),webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true}});win.setMenuBarVisibility(false);win.loadFile('index.html');win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',e=>e.preventDefault());win.on('close',e=>{if(!quitting&&state.closeToTray){e.preventDefault();win.hide();}});win.on('closed',()=>{win=null;if(!state.closeToTray)app.quit();});}
function openWorkspace(){quitting=false;if(!win||win.isDestroyed())createWindow();if(win.isMinimized())win.restore();win.show();win.focus();}
if(!app.requestSingleInstanceLock()){app.quit();}else{
app.on('second-instance',openWorkspace);
app.whenReady().then(()=>{try{load();}catch(error){dialog.showErrorBox('Could not open your workspace',error.message);app.quit();return;}createWindow();tray=new Tray(path.join(__dirname,'assets/icon.png'));tray.setToolTip(brand.productName);tray.setContextMenu(Menu.buildFromTemplate([{label:'Open '+brand.productName,click:openWorkspace},{type:'separator'},...modes.map(mode=>({label:mode,click:()=>setMode(mode)})),{type:'separator'},{label:'Quit '+brand.productName,click:()=>{quitting=true;app.quit();}}]));tray.on('double-click',openWorkspace);if(process.argv.includes('--smoke-test')){win.webContents.once('did-finish-load',async()=>{try{await new Promise(r=>setTimeout(r,2500));const result=await win.webContents.executeJavaScript(`(async()=>{const original=await desktop.invoke('state');const tasks=[...original.tasks,{id:'smoke',text:'Persistence verification',done:false}];await desktop.invoke('save',{tasks});const saved=await desktop.invoke('state');if(!saved.tasks.some(t=>t.id==='smoke'))throw Error('Persistence failed');await desktop.invoke('save',{tasks:original.tasks});const m=await desktop.invoke('metrics');if(!(m.memoryTotal>0))throw Error('Metrics failed');for(const name of ['Sparky','Tasks','Devices','Files','System','Settings','Home']){document.querySelector('[data-page="'+name+'"]').click();if(!document.querySelector('#content').textContent.trim())throw Error('Empty page '+name);}const lighting=await desktop.invoke('lighting');if(!lighting.available||lighting.devices.length<1)throw Error('Lighting discovery failed');document.querySelector('[data-page=Devices]').click();return {lightingDiscovery:true,persistence:true,navigation:true,cpu:m.cpuName,gpu:m.gpu?.name,gateway:await desktop.invoke('gateway')};})()`);fs.writeFileSync(path.join(__dirname,'smoke-result.json'),JSON.stringify(result,null,2));await new Promise(r=>setTimeout(r,1000));fs.writeFileSync(path.join(__dirname,'preview.png'),(await win.webContents.capturePage()).toPNG());}catch(e){fs.writeFileSync(path.join(__dirname,'smoke-result.json'),JSON.stringify({error:e.message}));}finally{quitting=true;app.quit();}});}});
}
app.on('before-quit',()=>quitting=true);
require('./workspace-main')({getState:()=>state,persist,isBusy:()=>busy,run});
ipcMain.handle('state',()=>({...state,appVersion:app.getVersion(),startup:app.getLoginItemSettings().openAtLogin,busy}));
ipcMain.handle('setup-save',(_,patch)=>{state.setup=setup.update(state.setup,patch);persist();return state.setup;});
ipcMain.handle('setup-check',(_,distro)=>distro==null?setup.inspect():setup.inspectWslHost(distro));
ipcMain.handle('setup-help',()=>({links:setup.links,steps:setup.steps,guide:fs.readFileSync(path.join(__dirname,'docs','fresh-pc-setup.md'),'utf8')}));
ipcMain.handle('setup-open-guide',(_,name)=>{if(!Object.hasOwn(setup.links,name))throw Error('Unknown setup guide.');return shell.openExternal(setup.links[name]);});
ipcMain.handle('save',(_,patch)=>{if(typeof patch.notes==='string')state.notes=patch.notes.slice(0,50000);if(typeof patch.closeToTray==='boolean')state.closeToTray=patch.closeToTray;if(patch.timer===null||Number.isFinite(patch.timer))state.timer=patch.timer;if(Array.isArray(patch.tasks))state.tasks=patch.tasks.slice(0,500).map(t=>({id:String(t.id),text:String(t.text).slice(0,500),done:!!t.done}));persist();return state;});
ipcMain.handle('mode',(_,mode)=>setMode(mode));
ipcMain.handle('startup',(_,enabled)=>{app.setLoginItemSettings({openAtLogin:!!enabled,path:process.execPath});return app.getLoginItemSettings().openAtLogin;});
ipcMain.handle('folder',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openDirectory']});if(!r.canceled){state.folders=[...new Set([...state.folders,r.filePaths[0]])].slice(-12);persist();}return state;});
ipcMain.handle('open-folder',(_,p)=>{if(!state.folders.includes(p))throw Error('Folder not selected');return shell.openPath(p);});
ipcMain.handle('export',async()=>{const r=await dialog.showSaveDialog(win,{defaultPath:'command-center-backup.json',filters:[{name:'JSON',extensions:['json']}]});if(!r.canceled)fs.writeFileSync(r.filePath,JSON.stringify(state,null,2));return !r.canceled;});
ipcMain.handle('gateway',async()=>{try{const h=parse(await claw(['health','--json']));return{ok:h.ok===true,discord:h.channels?.discord?.lifecycle||'unknown',checked:Date.now()};}catch{return{ok:false,discord:'unavailable',checked:Date.now()};}});
ipcMain.handle('lighting',async()=>{try{return{available:true,devices:await lighting.discover(),settings:state.lighting||{keys:[],color:'#00c9f4',brightness:35,sync:false},canRestore:!!state.lightingSnapshot?.length};}catch(e){return{available:false,error:e.message,devices:[]};}});
ipcMain.handle('lighting-apply',(_,options)=>applyLighting(options));
ipcMain.handle('lighting-sync',(_,enabled)=>{state.lighting={...state.lighting,sync:!!enabled};persist();return state;});
ipcMain.handle('lighting-restore',async()=>{const results=await lighting.restore(state.lightingSnapshot);log('Restored lighting: '+results.filter(x=>x.ok).length+' devices confirmed.');return results;});let previous=os.cpus();
ipcMain.handle('metrics',async()=>{const cpus=os.cpus();let idle=0,total=0;cpus.forEach((c,i)=>{const p=previous[i]||c;idle+=c.times.idle-p.times.idle;for(const k in c.times)total+=c.times[k]-p.times[k];});previous=cpus;let gpu=null;try{const out=await run('nvidia-smi.exe',['--query-gpu=name,utilization.gpu,temperature.gpu,memory.used,memory.total','--format=csv,noheader,nounits'],3000);const [name,usage,temp,used,size]=out.trim().split(',').map(x=>x.trim());gpu={name,usage:Number(usage),temp:Number(temp),used:Number(used),size:Number(size)};}catch{}let disk=null;try{const s=fs.statfsSync('C:\\');disk={total:s.blocks*s.bsize,free:s.bavail*s.bsize};}catch{}return{cpu:total?Math.round(100*(1-idle/total)):0,cpuName:cpus[0].model,memory:os.totalmem()-os.freemem(),memoryTotal:os.totalmem(),uptime:os.uptime(),gpu,disk,checked:Date.now()};});
ipcMain.handle('events',async()=>{try{return JSON.parse(await run('powershell.exe',['-NoProfile','-NonInteractive','-Command',"@(Get-WinEvent -FilterHashtable @{LogName='System';Id=41,1074,6008;StartTime=(Get-Date).AddDays(-7)} -ErrorAction SilentlyContinue | Select-Object -First 10 @{N='time';E={$_.TimeCreated.ToString('s')}},Id,Message) | ConvertTo-Json -Compress" ]));}catch{return[];}});
ipcMain.handle('chat',async(_,message)=>{if(hostManager.get().busy&&hostManager.get().operation==='prepare')throw Error('Host setup is still running. Wait for its checks to finish before sending a message.');if(busy)throw Error('Sparky is still responding');if(typeof message!=='string'||!message.trim()||message.length>12000)throw Error('Enter a message under 12,000 characters');busy=true;try{state.chat.push({role:'user',text:message,time:Date.now()});persist();const result=parse(await claw(['agent','--agent',state.connection?.agentId||'main','--session-key',state.session,'--message',message,'--json','--timeout','180'],200000));const payloads=result.result?.payloads||result.payloads||[];const answer=payloads.map(x=>x.text).filter(Boolean).join('\n\n');if(!answer)throw Error('Sparky returned no text. Check the gateway before retrying.');state.chat.push({role:'assistant',text:answer,time:Date.now()});log('Sparky replied in your desktop conversation.');return state;}catch(e){state.chat.push({role:'error',text:'Reply could not be confirmed. '+e.message,time:Date.now()});persist();throw e;}finally{busy=false;}});



