(() => {
  const api = window.desktop, brand = window.productBrand, $ = s => document.querySelector(s);
  let state, page = 'chat', gateway = {ok:false}, metrics, inventory, agents = [], selectedDistro = '', selectedAgent = 'main', lighting, working = false, sending = false;
  let draft = localStorage.getItem('workspace-draft') || sessionStorage.getItem('workspace-draft') || '', atBottom = true, scroll = 0;
  const icon = name => `<img class="icon" src="assets/fluent/${name}.svg" alt="">`;
  const mascot = () => '<img class="mascot" src="assets/mascot.png" alt="">';
  const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const agentName = () => state.connection?.agentName || (state.chat.length || state.conversations?.length ? 'Sparky' : state.setup.agentName);
  const deviceName = () => state.setup.deviceName || 'This computer';
  const status = () => gateway.ok ? 'Connected' : state.connection || state.chat.length ? 'Offline' : 'Setup needed';
  const currentTitle = () => state.chat.find(m=>m.role==='user')?.text.slice(0,58) || 'New conversation';
  let toastTimer, host={phase:'idle',busy:false}, hostTab='host', rolePicker=false;
  function toast(message){$('#toast').textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',6500);}
  function retain(){const messages=$('#messages');if(messages){scroll=messages.scrollTop;atBottom=messages.scrollHeight-messages.clientHeight-scroll<90;}}
  function resize(){const input=$('#chat-input');if(input){input.style.height='auto';input.style.height=Math.min(160,input.scrollHeight)+'px';}}
  function sidebar(){
    $('#sidebar').innerHTML=`<div class="brand">${mascot()}<h1>${esc(brand.productName)}</h1><p>Your agents, together.</p></div><button class="primary new-chat" data-action="new" ${sending?'disabled':''}>${icon('plus')}New conversation</button><div class="section-label">Your agent</div><button class="agent-link" data-page="chat">${mascot()}<span>${esc(agentName())}</span>${icon('view')}</button><div class="recents"><div class="section-label">Recent</div><button class="recent ${page==='chat'?'active':''}" data-page="chat">${icon('sessions')}<span>${esc(currentTitle())}</span></button>${(state.conversations||[]).map(c=>`<button class="recent" data-conversation="${esc(c.id)}" ${sending?'disabled':''}>${icon('sessions')}<span>${esc(c.title)}</span></button>`).join('')}</div><nav class="side-nav" aria-label="Main navigation">${[['files','files','Workspaces'],['tasks','tasks','Tasks'],['devices','system','Devices'],['setup','integrations','Host'],['settings','settings','Settings']].map(([key,img,label])=>`<button data-page="${key}" class="${page===key?'active':''}" ${page===key?'aria-current="page"':''}>${icon(img)}${label}</button>`).join('')}</nav><div class="device-footer">${icon('system')}<div><strong>${esc(deviceName())}</strong><small>${state.setup.role==='client'?'Client · pairing not configured':state.connection?'Local Host':'Local workspace'}</small></div></div>`;
  }
  function header(){
    const title=({chat:agentName(),files:'Workspaces',tasks:'Your priorities',devices:'Your devices',settings:'Settings',setup:'Your Host'})[page];
    $('#topbar').innerHTML=`<button class="icon-button mobile-menu" data-action="sidebar" aria-label="Toggle navigation">${icon('view')}</button>${mascot()}<div class="heading"><h2>${esc(title)}</h2><small><span class="dot ${gateway.ok?'online':''}"></span>${page==='setup'?'A little guidance, every step of the way.':gateway.ok?'Hosted on '+esc(deviceName()):'Your workspace is available offline'}</small></div><button class="status" data-page="setup"><span class="dot ${gateway.ok?'online':''}"></span><span class="status-label">${status()}</span></button><button class="icon-button" data-action="details" aria-label="Toggle conversation details" aria-expanded="${!$('#app').classList.contains('details-hidden')}">${icon('settings')}</button>`;
  }
  function details(){
    $('#details').innerHTML=`<h2>This conversation</h2><section class="details-section"><div class="detail-label">${icon('files')}Workspace</div><button class="folder-choice" data-page="files">${icon('files')}<span>${state.folders[0]?esc(state.folders[0].split(/[\\/]/).pop()):'Choose a workspace'}</span></button></section><section class="details-section"><div class="detail-label">${icon('system')}Available through</div><strong>${esc(deviceName())}</strong><p>${gateway.ok?'Local gateway connected':status()}</p><div class="detail-chips"><span class="chip">Conversation</span><button class="chip" data-page="setup">Connection setup</button></div></section><section class="details-section"><details open><summary>Connected devices</summary><dl><dt>This computer</dt><dd>${esc(deviceName())}</dd><dt>Connection</dt><dd>${state.connection?esc(state.connection.distro):state.chat.length?'Existing local Host':'Local setup not yet selected'}</dd></dl><button class="link" data-page="devices">View device details</button></details></section><section class="details-section"><p>Keep useful work close. Your conversations and selected folders stay on this computer.</p></section><small class="test-badge">${esc(brand.maker)}<br>${esc(state.appVersion||'0.6.0-alpha.1')} · Preview build</small>`;
  }
  function format(text){return String(text).split(/```/).map((s,i)=>i%2?`<pre><code>${esc(s.replace(/^\w*\n/,''))}</code></pre>`:s.split(/\n\n+/).map(p=>`<p>${esc(p).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>')}</p>`).join('')).join('');}
  function chat(){return `<section class="chat"><div class="messages" id="messages" aria-label="Conversation"><div class="thread">${state.chat.length?state.chat.map((m,i)=>`<article class="message ${esc(m.role)}">${m.role!=='user'?mascot():''}<div class="message-content"><div class="bubble">${format(m.text)}</div>${m.time?`<time>${new Date(m.time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time>`:''}${m.role==='assistant'?`<div class="message-actions"><button data-copy="${i}">${icon('files')}Copy</button></div>`:''}</div>${m.role==='user'?'<div class="user-avatar" aria-label="You">YOU</div>':''}</article>`).join(''):`<div class="empty-chat">${mascot()}<h2>What shall we make possible?</h2><p>Bring an idea. Find your next step.<br>${gateway.ok?esc(agentName())+' is here to work with you.':'Your space is ready. Connect your agent when you are.'}</p><div class="suggestions">${[['tasks','Make a plan','Help me turn my idea into a plan.'],['agents','Think it through','Help me think through a decision.'],['files','Start a project','Help me outline a new project.'],['analytics','Find some clarity','Help me organize my priorities.']].map(([img,label,prompt])=>`<button data-prompt="${prompt}">${icon(img)}${label}</button>`).join('')}</div>${!gateway.ok?'<button class="link" data-page="setup">Set up your agent</button>':''}</div>`}${sending?`<div class="thinking" role="status">${esc(agentName())} is working on your message…</div>`:''}</div></div><div class="composer-dock"><form id="chat-form" class="compose"><button type="button" class="icon-button" data-page="files" aria-label="Working folders">${icon('files')}</button><textarea id="chat-input" rows="1" maxlength="12000" placeholder="Message ${esc(agentName())}…" aria-label="Message your agent"></textarea><button class="primary" id="send" aria-label="Send message" ${sending||!draft.trim()?'disabled':''}>${icon('upload')}</button></form><div class="composer-note"><span>${sending?'Waiting for a reply':gateway.ok?'Connected to your local agent':'Drafts stay here while your agent is offline'}</span><span>Shift + Enter for a new line</span></div></div></section>`;}
  const intro=(title,copy)=>`<div class="page-intro"><h1>${title}</h1><p>${copy}</p></div>`;
  function files(){return intro('A place for your projects','Keep the folders you work with within reach.')+`<section class="panel"><div class="panel-head"><h2>Working folders</h2><button class="primary" data-action="folder">${icon('files')}Choose folder</button></div><p>These shortcuts open your selected folders. Agent file permissions are managed separately in OpenClaw.</p>${state.folders.map((p,i)=>`<div class="folder"><span>${esc(p)}</span><button data-folder="${i}">Open folder</button></div>`).join('')||'<div class="notice">No folders selected yet. Add a project to get started.</div>'}</section><section class="panel"><h2>Workspace notes</h2><textarea class="notes" id="notes" aria-label="Workspace notes" placeholder="Keep an idea for later…">${esc(state.notes)}</textarea><small id="notes-status">Saved on this computer</small></section>`;}
  function tasks(){return intro('Make room for what matters','A few clear priorities, right beside your conversations.')+`<section class="panel"><form class="task-form" id="task-form"><input id="task-input" aria-label="New task" maxlength="500" placeholder="What would you like to get done?" required><button class="primary">Add task</button></form>${state.tasks.map(t=>`<div class="task ${t.done?'done':''}"><input type="checkbox" data-task="${esc(t.id)}" aria-label="Complete ${esc(t.text)}" ${t.done?'checked':''}><span>${esc(t.text)}</span><button data-delete="${esc(t.id)}" aria-label="Delete task">${icon('delete')}</button></div>`).join('')||'<div class="notice">Add your first priority above.</div>'}</section>`;}
  function devices(){return intro('Your space, connected','Capabilities are discovered on this computer. Nothing is assumed from another PC.')+`<section class="panel"><div class="panel-head"><h2>${esc(deviceName())}</h2><button data-action="metrics">Refresh</button></div><p>${esc(metrics?.cpuName||'Reading processor information…')}</p><div class="device-metrics"><div><small>CPU usage</small><strong>${metrics?metrics.cpu+'%':'—'}</strong></div><div><small>Memory</small><strong>${metrics?Math.round(metrics.memory/metrics.memoryTotal*100)+'%':'—'}</strong></div><div><small>Graphics</small><strong style="font-size:14px">${esc(metrics?.gpu?.name||'No GPU telemetry')}</strong></div></div><button class="link" data-page="setup">Manage Host setup</button></section><section class="panel"><div class="panel-head"><h2>Lighting on this device</h2><button data-action="lighting">Scan lighting</button></div>${!lighting?'<p>Scan for controllers available through your local OpenRGB service.</p>':!lighting.available?'<div class="notice">No OpenRGB connection found. Lighting is optional; you can use your workspace without it.</div>':`<div class="lighting-grid">${lighting.devices.map(d=>`<label class="panel"><input type="checkbox" class="rgb-device" value="${esc(d.key)}" ${lighting.settings.keys.includes(d.key)?'checked':''} ${d.supported?'':'disabled'}> ${esc(d.name)}<p>${d.leds} configured LEDs · ${esc(d.activeMode)}</p></label>`).join('')}</div><div class="lighting-controls"><label>Color <input type="color" id="rgb-color" value="${esc(lighting.settings.color)}"></label><label>Brightness <input id="rgb-brightness" type="range" min="0" max="100" value="${lighting.settings.brightness}"></label><button class="primary" data-action="lighting-apply">Apply lighting</button><button data-action="lighting-restore" ${lighting.canRestore?'':'disabled'}>Restore previous</button></div><p>Check the physical lights after applying. Discovery does not prove every attached LED can be controlled.</p>`}</section>`;}
  function settings(){return intro('Make it yours','A quieter workspace, built around the way you work.')+`<section class="panel"><h2>Your connection</h2><p>Your agent uses the tools and permissions configured in OpenClaw. Foxsocket does not sandbox or remove those permissions.</p><div class="setting"><span><strong>${esc(agentName())}</strong><small>${state.connection?esc(state.connection.distro)+' · '+esc(state.connection.agentId):state.chat.length?'Existing local agent · manage background Host':'Complete setup to connect a local agent'}</small></span><button data-page="setup">Open setup</button></div></section><section class="panel"><h2>App behavior</h2><label class="setting"><span><strong>Open when I sign in</strong><small>Bring up this workspace when you start Windows.</small></span><input id="startup-setting" type="checkbox" ${state.startup?'checked':''}></label><label class="setting"><span><strong>Keep running after closing</strong><small>When off, closing the window quits this app. The Host service runs separately.</small></span><input id="close-tray" type="checkbox" ${state.closeToTray?'checked':''}></label><label class="setting"><span><strong>Interface motion</strong><small id="motion-note">Brief transitions and gentle button feedback.</small></span><input id="interface-motion" type="checkbox" ${localStorage.getItem('applied-ai-interface-motion')!=='off'?'checked':''}></label></section><section class="panel"><h2>Your data</h2><div class="setting"><span><strong>Export workspace backup</strong><small>Save conversations, notes and tasks. Excludes connections, session keys and hardware settings. This file contains private conversation text.</small></span><div class="actions"><button data-action="export">Export content</button><button data-action="import">Restore content</button></div></div><div class="setting"><span><strong>Setup help</strong><small>Available before your agent is connected.</small></span><button data-action="help">Read guide</button></div></section><small>${esc(brand.maker)} · ${esc(state.appVersion||'0.6.0-alpha.1')}<br>Working product name: ${esc(brand.productName)}</small>`;}
  function setupPage(){
    const step=state.setup.step||'role', role=state.setup.role||(state.chat.length?'host':null);
    const nav=[['role','This PC'],['requirements','Readiness'],['runtime','OpenClaw'],['provider','AI access'],['service','Background'],['conversation','Connect']];
    let body='';
    if(rolePicker||!role) body=`${intro('Your agents. Your workspace.','Start with what you want this computer to do. We’ll help with the rest.')}<label class="field">Name this computer<input id="device-name" value="${esc(deviceName())}" maxlength="64"></label><div class="role-grid"><button class="role-card ${role==='host'?'selected':''}" data-role="host">${icon('system')}<strong>Set up a Host</strong><p>Run your own agent here. Connect your AI access, choose permissions, and start a conversation.</p></button><button class="role-card ${role==='client'?'selected':''}" data-role="client">${icon('integrations')}<strong>Client — coming next</strong><p>Reach an agent on another computer. Private pairing is coming in a later test build.</p></button></div><p class="muted">Your agent can have its own name. This alpha connects an existing OpenClaw agent. Guided first-time account setup is still in development.</p>`;
    else if(role==='client') body=intro('Your Host, within reach','This preview focuses on setting up a local Host.')+`<section class="panel"><h2>Client pairing is not available yet</h2><p>You can prepare Tailscale and use your local notes and tasks. This build cannot connect to a remote Host.</p><div class="actions"><button data-guide="tailscale">Tailscale instructions</button><button data-step="role">Choose Host instead</button><button data-page="files">Open local workspace</button></div></section>`;
    else return window.hostSetup.view({state,inventory,distro:selectedDistro,host,tab:hostTab,agents,selectedAgent,agentName:agentName()});
    return `<div class="setup-progress">${nav.map(([key,label])=>`<button data-step="${key}" class="${step===key?'current':''}">${label}</button>`).join('')}</div>${body}<div class="actions"><button class="link" data-action="help">Need a hand? Read the step-by-step guide</button><button class="link" data-page="chat">Use workspace for now</button></div>`;
  }
  function render(){
    retain();sidebar();header();details();document.body.dataset.page=page;
    $('#content').innerHTML=page==='chat'?chat():`<div class="page-scroll"><div class="page-inner">${({files,tasks,devices,settings,setup:setupPage})[page]()}</div></div>`;
    if(page==='chat'){$('#chat-input').value=draft;resize();const m=$('#messages');m.scrollTop=atBottom?m.scrollHeight:scroll;}
    window.appEffects?.render(page);window.releaseUpdates?.render();
  }
  async function refresh(){try{gateway=await api.invoke('gateway');}catch{gateway={ok:false};}header();details();const note=$('.composer-note span');if(note&&!sending)note.textContent=gateway.ok?'Connected to your local agent':'Drafts stay here while your agent is offline';}
  async function checkHost(){if(!selectedDistro)return;host={phase:'checking',busy:true};render();try{await api.invoke('host-check',selectedDistro);}catch(e){host={phase:'attention',busy:false,error:e.message};render();}}
  async function checkPc(){[inventory,metrics]=await Promise.all([api.invoke('setup-check'),api.invoke('metrics')]);if(!inventory.wsl?.distributions.some(d=>d.name===selectedDistro))selectedDistro=inventory.wsl?.distributions[0]?.name||'';}
  async function goStep(step){rolePicker=step==='role';state.setup=await api.invoke('setup-save',{step});if(['runtime','conversation'].includes(step)&&!inventory)await checkPc();render();}
  async function findAgents(){if(!inventory)await checkPc();selectedDistro=$('#distro')?.value||selectedDistro;if(!selectedDistro)throw Error('Choose a Linux environment first.');agents=await api.invoke('setup-agents',selectedDistro);selectedAgent=agents[0]?.id||'';render();toast(agents.length?'Your configured agents are available below.':'No agents found. Complete OpenClaw onboarding first.');}
  document.addEventListener('click',async event=>{
    const b=event.target.closest('button');if(!b||b.disabled)return;
    if(b.dataset.action==='sidebar'){$('#app').classList.toggle('sidebar-open');return;}
    if(b.dataset.action==='details'){if(innerWidth<=1200)$('#app').classList.toggle('details-overlay');else $('#app').classList.toggle('details-hidden');header();return;}
    if(b.id==='close-help'){$('#help').close();return;}
    if(b.dataset.prompt){draft=b.dataset.prompt;$('#chat-input').value=draft;$('#chat-input').dispatchEvent(new Event('input',{bubbles:true}));$('#chat-input').focus();return;}
    if(b.dataset.page){page=b.dataset.page;$('#app').classList.remove('sidebar-open');render();if(page==='setup'&&(state.setup.role==='host'||state.chat.length)&&!inventory){checkPc().then(()=>{render();return checkHost();}).catch(e=>toast(e.message));}return;}
    if(b.dataset.hostTab){hostTab=b.dataset.hostTab;render();return;}
    if(working)return;working=true;b.disabled=true;
    try{
      if(b.dataset.copy!==undefined){await navigator.clipboard.writeText(state.chat[Number(b.dataset.copy)].text);toast('Response copied.');}
      if(b.dataset.role){rolePicker=false;state.setup=await api.invoke('setup-save',{role:b.dataset.role,deviceName:$('#device-name').value});await checkPc();render();if(state.setup.role==='host')await checkHost();}
      if(b.dataset.step)await goStep(b.dataset.step);
      if(b.dataset.host==='scan'){await checkPc();render();await checkHost();}
      if(b.dataset.host==='check')await checkHost();
      if(b.dataset.host==='prepare'){if(sending)throw Error('Wait for the current reply to finish.');host={phase:'checking',busy:true};render();try{await api.invoke('host-prepare',selectedDistro);}catch(e){host={phase:'attention',busy:false,error:e.message};render();}}
      if(b.dataset.guide)await api.invoke('setup-open-guide',b.dataset.guide);
      if(b.dataset.command){await api.invoke('setup-command',{step:b.dataset.command,distro:selectedDistro,copyOnly:b.dataset.copyOnly==='true'});toast(b.dataset.copyOnly?'Command copied.':'Command copied. Paste it into the terminal, then press Enter.');}
      if(b.dataset.conversation){state={...state,...await api.invoke('conversation-select',b.dataset.conversation)};draft='';localStorage.removeItem('workspace-draft');sessionStorage.removeItem('workspace-draft');page='chat';render();}
      if(b.dataset.folder!==undefined)await api.invoke('open-folder',state.folders[Number(b.dataset.folder)]);
      if(b.dataset.delete){state.tasks=state.tasks.filter(t=>t.id!==b.dataset.delete);state={...state,...await api.invoke('save',{tasks:state.tasks})};render();}
      switch(b.dataset.action){
        case 'new': state={...state,...await api.invoke('conversation-new')};draft='';localStorage.removeItem('workspace-draft');sessionStorage.removeItem('workspace-draft');page='chat';render();break;
        case 'folder':state={...state,...await api.invoke('folder')};render();break;
        case 'export':if(await api.invoke('export'))toast('Workspace backup saved.');break;
        case 'import':{if(draft.trim())throw Error('Save or clear your message draft before restoring.');const restored=await api.invoke('import');if(restored){state={...state,...restored};page='chat';render();toast('Content restored. Your agent connection is unchanged; imported history starts fresh agent sessions.');}break;}
        case 'help':$('#help-text').textContent=(await api.invoke('setup-help')).guide;$('#help').showModal();break;
        case 'check-pc':await checkPc();render();break;
        case 'find-agents':await findAgents();break;
        case 'connect':state={...state,...await api.invoke('setup-connect',{distro:selectedDistro,agentId:$('#agent-choice').value})};page='chat';await refresh();render();break;
        case 'metrics':metrics=await api.invoke('metrics');render();break;
        case 'lighting':lighting=await api.invoke('lighting');render();break;
        case 'lighting-apply':{const r=await api.invoke('lighting-apply',{keys:[...document.querySelectorAll('.rgb-device:checked')].map(c=>c.value),color:$('#rgb-color').value,brightness:Number($('#rgb-brightness').value),sync:lighting.settings.sync||false});state={...state,...r.state};lighting=await api.invoke('lighting');render();toast('Settings sent. Confirm the physical lights on this PC.');break;}
        case 'lighting-restore':await api.invoke('lighting-restore');lighting=await api.invoke('lighting');render();break;
      }
    }catch(error){toast(error.message);}finally{working=false;if(b.isConnected)b.disabled=false;}
  });
  let noteTimer;
  document.addEventListener('input',event=>{
    if(event.target.id==='chat-input'){draft=event.target.value;localStorage.setItem('workspace-draft',draft);sessionStorage.setItem('workspace-draft',draft);$('#send').disabled=sending||!draft.trim();resize();}
    if(event.target.id==='notes'){state.notes=event.target.value;clearTimeout(noteTimer);$('#notes-status').textContent='Saving…';noteTimer=setTimeout(async()=>{try{await api.invoke('save',{notes:state.notes});if($('#notes-status'))$('#notes-status').textContent='Saved on this computer';}catch{toast('Could not save your note.');}},300);}
  });
  document.addEventListener('change',async event=>{try{
    if(event.target.id==='distro'){selectedDistro=event.target.value;localStorage.setItem('host-distro',selectedDistro);agents=[];selectedAgent='';host={phase:'idle',busy:false};render();await checkHost();}
    if(event.target.id==='agent-choice')selectedAgent=event.target.value;
    if(event.target.id==='startup-setting')state.startup=await api.invoke('startup',event.target.checked);
    if(event.target.id==='close-tray'){state.closeToTray=event.target.checked;await api.invoke('save',{closeToTray:state.closeToTray});}
    if(event.target.dataset.task){state.tasks.find(t=>t.id===event.target.dataset.task).done=event.target.checked;state={...state,...await api.invoke('save',{tasks:state.tasks})};render();}
  }catch(error){toast(error.message);}});
  document.addEventListener('submit',async event=>{
    event.preventDefault();
    if(event.target.id==='task-form'){const value=$('#task-input').value.trim();if(!value)return;try{state.tasks.push({id:crypto.randomUUID(),text:value,done:false});state={...state,...await api.invoke('save',{tasks:state.tasks})};render();}catch(error){toast(error.message);}return;}
    if(event.target.id!=='chat-form'||sending)return;
    const message=$('#chat-input').value.trim();if(!message)return;
    sending=true;state.chat.push({role:'user',text:message,time:Date.now()});draft='';$('#chat-input').value='';localStorage.removeItem('workspace-draft');sessionStorage.removeItem('workspace-draft');atBottom=true;render();
    try{state={...state,...await api.invoke('chat',message)};gateway={ok:true};}
    catch(error){try{state={...state,...await api.invoke('state')};}catch{}draft=message;localStorage.setItem('workspace-draft',draft);sessionStorage.setItem('workspace-draft',draft);toast('Reply not confirmed. Your draft is retained; check the conversation before sending again.');}
    finally{sending=false;if(page==='chat'){$('#chat-input').value=draft;render();}}
  });
  document.addEventListener('keydown',event=>{if(event.target.id==='chat-input'&&event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();$('#chat-form').requestSubmit();}if((event.ctrlKey||event.metaKey)&&event.key==='k'){event.preventDefault();page='chat';render();$('#chat-input').focus();}});
  api.onHostProgress?.(next=>{host=next;if(page==='setup'&&!rolePicker&&(state?.setup.role==='host'||state?.chat.length))render();});
  api.onState(next=>{state={...state,...next};render();});
  (async()=>{try{state=await api.invoke('state');state.conversations||=[];sending=!!state.busy;selectedDistro=state.connection?.distro||localStorage.getItem('host-distro')||(state.chat.length?'Ubuntu-24.04':'');page=state.connection||state.chat.length||state.conversations.length?'chat':'setup';render();$('#startup').remove();refresh();api.invoke('host-status').then(value=>{host=value;if(page==='setup')render();}).catch(()=>{});if(page==='setup'&&state.setup.role==='host'){await checkPc();render();await checkHost();}api.invoke('metrics').then(value=>metrics=value).catch(()=>{});setInterval(()=>{if(!document.hidden)refresh();},30000);}catch(error){console.error('Workspace initialization:',error.message);$('#startup').innerHTML='<h1>Could not open your workspace</h1><p>Your saved files have not been reset.</p><button id="reload">Try again</button>';$('#reload').onclick=()=>location.reload();}})();
})();
